name: growrichgroup_dashboard
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  auto_route: ^8.0.3
  bottom_sheet: ^4.0.4
  carousel_slider: ^4.2.1
  clipboard: ^0.1.3
  cloud_firestore: ^4.17.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.8
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.1
  flutter_local_notifications: ^17.1.1
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  gradient_borders: ^1.0.0
  image_picker: ^1.1.1
  intl: ^0.19.0
  lottie: ^3.0.0
  provider: ^6.1.2
  pull_to_refresh: ^2.0.0
  rive: ^0.13.1
  riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  responsive_sizer: ^3.3.1
  url_launcher: ^6.2.6
  video_player: ^2.8.3
  permission_handler: ^11.3.1
  dartz: ^0.10.1

  
dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: null
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

  rename: ^3.0.2

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
